### ISSUE TITLE
Out of order arguments by user

### ISSUE THREAD

**Issue by eslerm** [RedHatProductSecurity/cvelib#101]
I was in a tough spot when I entered a command incorrectly.

To look up another user at your org, you can run:
```
cve user -u foo@bar.com
```

And a user can be deactivated by:
```
cve user update --mark-inactive -u foo@bar.com
```

If the wrong argument order is used (and the warning is ignored), $CVE_USER will be inactivated:
```
eslerm@aeon:~$ cve user -u foo@bar.com update --mark-inactive
You are about to update the eslerm@bar.com user with the following changes:

- active: false

Do you want to continue? [y/N]: y

User updated.
eslerm@aeon:~$ cve org users
ERROR: 401 Client Error: Unauthorized for url: https://cveawg.mitre.org/api/org/canonical/users
DETAILS: {'error': 'UNAUTHORIZED', 'message': 'Unauthorized'}
```

:sweat_smile:

**Comment by mprpic** [comment]
I think this was already sort of addressed in https://github.com/RedHatProductSecurity/cvelib/releases/tag/1.5.0 because after that release, the `-u` option is required (even if you're updating your own user) for both `update` and `reset-token`. So the second command should complain that you did not specify the `-u` option for it.

@eslerm Can you confirm which version of cvelib you're using?

**Comment by eslerm** [comment]
Ah! Thanks @mprpic! I was using an older version.
